request deniel review
NeonGeckoCom/neon-lang-plugin-cld3 pull request #5
Opened 2022-07-14 14:33 UTC by NeonDmitry

2022-07-14 14:41 UTC, NeonDmitry commented
@NeonDaniel please review this, I has no access to add reviewers

2022-07-14 16:54 UTC, NeonDaniel requested changes
Couple small changes noted

2022-07-14 16:54 UTC, NeonDaniel commented on .github/workflows/unit_tests.yml
> +      - name: Get Credential
This `Get Credential` step can be removed for this plugin

2022-07-14 16:54 UTC, NeonDaniel commented on .gitignore
> +
These lines can be replaced by just `.idea/`

2022-07-14 16:54 UTC, NeonDaniel commented on tests/test_detect.py
> +import json
This added file needs a license notice (https://gist.github.com/NeonDaniel/1652cbc98717643db50583d80274bca3#file-header-bsd-3-license)

2022-07-18 07:38 UTC, NeonDmitry commented on tests/test_detect.py
> +import json
@NeonDaniel  resolved this small changes as you say, sir!

2022-07-18 16:55 UTC, NeonDaniel approved these changes

2022-07-18 16:55 UTC, merged